version: "2"

run:
  timeout: 5m
  tests: false  # Don't lint test files

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
  settings:
    errcheck:
      # Don't check for errors on these functions (common patterns)
      exclude-functions:
        - (io.Closer).Close
        - (*os.File).Close
        - (net/http.ResponseWriter).Write
        - (*database/sql.Rows).Close
        - (*database/sql.Tx).Rollback
        - (*database/sql.DB).Close
        - (encoding/json.Unmarshal)