#!/bin/bash

echo "Testing Costco Authentication"
echo "=============================="
echo ""
echo "The Costco client needs to authenticate with real credentials to get valid tokens."
echo "The tokens that were saved earlier were test/mock tokens from unit tests."
echo ""
echo "To authenticate and save real tokens, you need to:"
echo ""
echo "1. Set your Costco password as an environment variable:"
echo "   export COSTCO_PASSWORD='your-actual-password'"
echo ""
echo "2. Run the CLI to authenticate and save tokens:"
echo "   cd /Users/erickshaffer/code/costco-go"
echo "   go run ./cmd/costco-cli -cmd orders -start 2025-09-01 -end 2025-09-09"
echo ""
echo "3. Once authenticated, the tokens will be saved to ~/.costco/tokens.json"
echo "   and will be reused automatically for future requests"
echo ""
echo "4. Then you can test the integration:"
echo "   cd /Users/erickshaffer/code/monarchmoney-sync-backend"
echo "   go run cmd/costco-example/main.go -days=7"
echo ""
echo "The client IS configured to use saved tokens - it just needs real ones first!"